/** Catálogo Siscad 3.6 (ParametrosRh) — motivos / submotivos oficiais. */

export const SISCAD_MOTIVOS = [
  'ATO DE IMPROBIDADE',
  'ATO DE INDISCIPLINA OU INSUBORDINACAO',
  'ATO EM DESACORDO COM O REGULAMENTO DA EMPRESA',
  'ATO LESIVO DA HONRA E BOA FAMA CONTRA CLIENTE',
  'ATO LESIVO DA HONRA E BOA FAMA CONTRA EMPREGADOR',
  'DESIDIA NO DESEMPENHO DAS FUNCOES',
  'INCONTINENCIA DE CONDUTA OU MAU PROCEDIMENTO',
] as const;

export type SiscadMotivo = (typeof SISCAD_MOTIVOS)[number];

export const SISCAD_SUBMOTIVOS_POR_MOTIVO: Record<SiscadMotivo, readonly string[]> = {
  'ATO DE IMPROBIDADE': [
    'REALIZAR VENDA INDEVIDA',
    'REALIZAR VENDA SEM CONSENTIMENTO DO CLIENTE',
  ],
  'ATO DE INDISCIPLINA OU INSUBORDINACAO': [
    'DESRESPEITAR O SUPERIOR HIERARQUICO',
    'PORTAR OBJETO NAO PERMITIDO E/OU ALIMENTO NA ESTACAO DE TRABALHO',
  ],
  'ATO EM DESACORDO COM O REGULAMENTO DA EMPRESA': [
    'DEIXAR DE CUMPRIR OS PROCEDIMENTOS PADROES DE ATENDIMENTO E REGISTRO SISTEMICO',
  ],
  'ATO LESIVO DA HONRA E BOA FAMA CONTRA CLIENTE': [
    'DENEGRIR A IMAGEM DO CLIENTE CONTRATANTE DURANTE ATENDIMENTO',
  ],
  'ATO LESIVO DA HONRA E BOA FAMA CONTRA EMPREGADOR': [
    'DENEGRIR A IMAGEM DA EMPRESA DURANTE ATENDIMENTO',
  ],
  'DESIDIA NO DESEMPENHO DAS FUNCOES': [
    'AGIR DE FORMA DESRESPEITOSA COM O CLIENTE DURANTE ATENDIMENTO',
    'ARGUMENTAR COM INVERDADES DURANTE ATENDIMENTO',
    'ATRASOS RECORRENTES NA ENTRADA',
    'DEIXAR DE CUMPRIR A JORNADA LABORAL',
    'DEIXAR DE CUMPRIR ORDEM LEGAL DE SUPERIOR HIERARQUICO',
    'DEIXAR DE CUMPRIR OS PROCEDIMENTOS PADROES DE ATENDIMENTO E REGISTRO SISTEMICO',
    'DEIXAR DE GRAVAR O SCRIPT ROD',
    'DEIXAR DE REGISTRAR PONTO',
    'DESCONECTAR LIGACOES',
    'EXCEDER TEMPO LIMITE DE PAUSA',
    'FALTAR INJUSTIFICADAMENTE AO TRABALHO',
    'FORNECER INFORMACOES INCOMPLETAS AO CLIENTE DURANTE ATENDIMENTO',
    'FORNECER INFORMACOES INCORRETAS AO CLIENTE DURANTE ATENDIMENTO',
    'OMITIR ATENDIMENTO',
    'OMITIR INFORMACOES AO CLIENTE DURANTE ATENDIMENTO',
    'RETER LIGACAO APOS CONTATO COM CLIENTE',
    'SAÍDA ANTECIPADA',
    'UTILIZAR PAUSA INDEVIDAMENTE',
  ],
  'INCONTINENCIA DE CONDUTA OU MAU PROCEDIMENTO': ['USAR APARELHO ELETRONICO NA OPERACAO'],
};

/** Escalas nominais do Siscad (referência histórica; a UI usa a escala pedagógica 3F). */
export const SISCAD_ESCALAS = [
  '1A ADVERTENCIA',
  '2A ADVERTENCIA',
  '3A ADVERTENCIA',
  '1A SUSPENSAO',
  '2A SUSPENSAO',
  '3A SUSPENSAO',
] as const;

const EMPTY_SUBS: readonly string[] = [];

export function submotivosDoMotivo(motivo: string): readonly string[] {
  const key = motivo as SiscadMotivo;
  return SISCAD_SUBMOTIVOS_POR_MOTIVO[key] ?? EMPTY_SUBS;
}

/** Texto legível para o corpo do PDF (mantém sentido jurídico do Siscad). */
export function rotuloDocumentoSubmotivo(sub: string): string {
  return sub
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/(^\w)|(\s\w)/g, (m) => m.toUpperCase());
}
